//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriationSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureUnit
    {
        public MeasureUnit()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string MeasUnit { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
