//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriationSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public Parameter()
        {
            this.ParameterValues = new HashSet<ParameterValue>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Measure_Unit { get; set; }
        public int User_Id { get; set; }
    
        public virtual ICollection<ParameterValue> ParameterValues { get; set; }
    }
}
