//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriationSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Parameter
    {
        public Parameter()
        {
            this.ParameterValues = new HashSet<ParameterValue>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage="Ñan not be empty")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "The string length must be between 2 and 50 characters")]
        [Display(Name= "Parameter name")]
        public string Name { get; set; }

        [Display(Name = "Parameter unit")]
        public string Measure_Unit { get; set; }
        public int User_Id { get; set; }
    
        public virtual ICollection<ParameterValue> ParameterValues { get; set; }
    }
}
